// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PauloOlivo_ExamenP1.Data;

#nullable disable

namespace PauloOlivo_ExamenP1.Migrations
{
    [DbContext(typeof(PauloOlivo_ExamenP1Context))]
    [Migration("20241028145516_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PauloOlivo_ExamenP1.Models.PO_Tablita", b =>
                {
                    b.Property<int>("PO_TablitaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PO_TablitaId"));

                    b.Property<string>("PO_Apellido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("PO_Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("PO_Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PO_Precio")
                        .HasColumnType("bit");

                    b.Property<float?>("PO_Tabla")
                        .IsRequired()
                        .HasColumnType("real");

                    b.HasKey("PO_TablitaId");

                    b.ToTable("PO_Tablita");
                });
#pragma warning restore 612, 618
        }
    }
}
